name: e2e Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    test:
        timeout-minutes: 20
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm install
            - name: Starting the WordPress Environment
              run: npm run env start
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run e2e tests
              run: npm run test:e2e
            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
